### ISSUE TITLE
breyta 2023 í 2024

### ISSUE THREAD

**Issue by hanndoddi** [Fab-Lab-Island/FLI_Boot_Camp_2024#1]
Það þarf að breyta ártalinu það er vitlaust

**Comment by FabLabSaudarkrokur** [comment]
fávitinn hann Magús var á undan mér

**Comment by arnib13** [comment]
Hér vantar uppfærslu á ártali -> https://github.com/Fab-Lab-Austurland/FLI-Boot-Camp-2023/blob/main/index.html

**Comment by hanndoddi** [comment]
Er þetta ekki bara komið?
