### ISSUE TITLE
Kayak ferð vandamál 

### ISSUE THREAD

**Issue by hanndoddi** [Fab-Lab-Island/FLI_Boot_Camp_2024#18]
ég er búin að gera alls konar tilraunir til að vinna undirsíðuna fyrir hópefli/kajakferðina. Ekkert hefur gengið. Ætli það sé hægt að bakka og finna möppuna sem ég bjó til með upplýsingum um ferðina? Hún birtist samt aldrei á heimasíðunni.

Svo skrifaði ég póst um að vinnustofunni/Bootcampinu væri lokið og setti inn mynd þar af hópnum. Ég skil ekki af hverju sú mynd birtist ekki. Taldi mig hafa gert þetta á réttan hátt.

Vandamálið er að ég hef ekki enn áttað mig á bestu leiðinni við að búa til möppu. Ef ég smelli á ,,projects" í trénu vinstra megin og vel svo að búa til möppu með því að smella á möpputáknið uppi með plúsmerkinu virðist mappan ekki vistast. Ég ákvað því að búa strax til skjal undir möppunni og skrifa í það eins og það væri undirsíðan. Er það kannski ekki rétt leið?

**Comment by OlofH2** [comment]
Svarið er fundið: 
Þegar unnið er almennt með möppur og skjöl í tölvum er mappan oft búin til fyrst og skjölin í möppunni þar á eftir. Það þarf að fara öfuga leið við þetta þegar undirsíður eru búnar til í veftrénu í Web Editor. Þetta er því rétta leiðin:
- Smella á yfirsíðuna (t.d. projects)
- Velja að búa til nýtt skjal (undirsíðu) og nota til þess táknið sem er eins og blað í laginu með plústákni.
- Byrja að skrifa/búa til textann á síðuna í vinnuglugganum.
- Tengja svo undirsíðuna með því að fara inn í Readme.md skjalið, skrifa nafn síðunnar í hornklofa og nafn md skjalsins í sviga þar á eftir.
- Það er líka hægt að draga md möppuna yfir í Readme skjalið og halda shift takkanum inni þegar músarhnappnum er sleppt. Þá er skjalið/undirsíðan komin inn og einungis þörf á að skrifa heiti undirsíðunnar í hornklofann.
